### ISSUE TITLE
Create a UI for creating NFT and Token pool.

### ISSUE THREAD

**Issue by bisbist** [bisbist/sudoswap-frontend#5]
Note: Use the LSSVMPairFactory contract to implement the above functionality.

### TODO:

- [x] Create a simple react-UI to connect to the meta-mask to execute transactions.
- [x] Create a Token-NFT pair pool for the following 4 combination:
1. Missing Enumerable | ETH
2. Missing Enumerable | ERC20
3. Enumerable | ETH
4. Enumerable | ERC20

- [x] Add UI button to create a New Pool that can do the following:
1. Create a pool to Buy NFTs with tokens.
2. Create a pool to Sell NFTs for tokens.
3. Create a pool that can do both and earn trading fees.
